version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: cornice
    versions:
    - 5.0.3
    - 5.1.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: more-itertools
    versions:
    - 8.6.0
