language: python
python:
<<<<<<< HEAD
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database neuralknight;" -U postgres

#set some environment variables
env:
  - TEST_DATABASE_URL='postgres://127.0.0.1:5432/neuralknight'

# command to install dependencies
install:
  - pip install -e .[testing]

# commands to run tests
script:
  - pytest

notifications:
  email: false
=======
- '3.6'
cache: pip
services:
- postgresql
before_script:
- psql -c "create database neuralknight_test;" -U postgres
env:
- TEST_DATABASE_URL='postgres://127.0.0.1:5432/neuralknight_test'
install:
- pip install -e .[testing]
script:
- pytest
deploy:
  provider: heroku
>>>>>>> Initialize travis.
